---
default_install_hook_types: [pre-push]

exclude: 'LICENSES/'

# See: https://pre-commit.com/hooks.html
repos:
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 41.21.3
    hooks:
      - id: renovate-config-validator
