# SPDX-FileCopyrightText: 2022 - 2024 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- block:
    - when: postgres_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - when: postgres_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"
  tags:
    - setup-all
    - setup-postgres
    - install-all
    - install-postgres

- block:
    - when: not postgres_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-postgres

- block:
    - when: postgres_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/import_postgres.yml"
  tags:
    - import-postgres

- block:
    - when: postgres_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/import_generic_sqlite_db.yml"
  tags:
    - import-generic-sqlite-db

- block:
    - when: postgres_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/upgrade_postgres.yml"
  tags:
    - upgrade-postgres

- block:
    - when: postgres_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/run_vacuum.yml"
  tags:
    - run-postgres-vacuum
