# SPDX-FileCopyrightText: 2022 - 2024 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of Postgres systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ postgres_identifier }}.service"
  register: postgres_service_stat

- name: Uninstall Postgres systemd service and scripts
  when: postgres_service_stat.stat.exists | bool
  block:
    - name: Ensure Postgres systemd service is stopped
      ansible.builtin.service:
        name: "{{ postgres_identifier }}"
        state: stopped
        daemon_reload: true

    - name: Ensure Postgres systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ postgres_identifier }}.service"
        state: absent

    - name: Ensure Postgres scripts do not exist
      ansible.builtin.file:
        path: "{{ postgres_bin_path }}"
        state: absent

    - name: Ensure Postgres container network does not exist via community.docker.docker_network
      when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
      community.docker.docker_network:
        name: "{{ postgres_container_network }}"
        state: absent

    - name: Ensure Postgres container network does not exist via ansible.builtin.command
      when: devture_systemd_docker_base_container_network_creation_method == 'command'
      ansible.builtin.command:
        cmd: >-
          {{ devture_systemd_docker_base_host_command_docker }} network rm
          {{ postgres_container_network }}
      register: network_deletion_result
      changed_when: postgres_container_network in network_deletion_result.stdout

- name: Check existence of Postgres local data path
  ansible.builtin.stat:
    path: "{{ postgres_data_path }}"
  register: postgres_data_path_stat

# We just want to notify the user. Deleting data is too destructive.
- name: Notify if Postgres local data remains
  when: postgres_data_path_stat.stat.exists | bool
  ansible.builtin.set_fact:
    devture_playbook_runtime_messages_list: |
      {{
        devture_playbook_runtime_messages_list | default([])
        +
        [
          "Note: You are not using a local Postgres database, but some old data remains from before in `{{ postgres_data_path }}`. Feel free to delete it."
        ]
      }}
